#!/bin/bash
# 
# The wrapper for amixer command to notify about the volume and mute status
# 

amixer "$@"

delay=1000

vol_pars=($(amixer -M get Master | awk -F"[][]" '/dB/ { print $2 " " $6 }'))
volume="${vol_pars[0]}"
case "${vol_pars[1]}" in
    "on") muted="No" ;;
    "off") muted="Yes" ;;
esac
notify-send -t $delay "Volume" "Current level: $volume\nMuted: $muted"
