#!/bin/sh

if command -v sxiv >/dev/null 2>&1; then
    if [ -d "${@: -1}" ] || [ -h "${@: -1}" ]; then
        /usr/bin/sxiv -t "$@"
    else
        /usr/bin/sxiv "$@"
    fi
elif command -v feh >/dev/null 2>&1; then
    feh "$@"
else
    echo "Please install SXIV or FEH!"
fi
