#!/bin/bash

path=~/Pictures/screenshots/$(date +%F_%H%M%S_%N).png

activeWinLine=$(xprop -root | grep "_NET_ACTIVE_WINDOW(WINDOW)")
activeWinId=${activeWinLine:40}
import -window "$activeWinId" "$path"
xclip -selection clipboard -t image/png "$path"
notify-send "PrintScreen" "Active window snapshoted!"
