#!/bin/bash

path=~/Pictures/screenshots/$(date +%F_%H%M%S_%N).png

import -window root "$path"
xclip -selection clipboard -t image/png "$path"
notify-send "PrintScreen" "Screen image saved to ${path}"
