#!/bin/sh

dwm_config=~/Projects/dwm/config.h

# Settings
font="DejaVuSansMono:size=9"
fgcolor="$(grep "normfgcolor\[\]" "$dwm_config" | cut -d'=' -f2 | sed 's/.$//; s/"//g')"
bgcolor="$(grep "normbgcolor\[\]" "$dwm_config" | cut -d'=' -f2 | sed 's/.$//; s/"//g')"
dzen_width=500
dzencmd="dzen2 -p -w "$dzen_width" -fn "$font" -fg "$fgcolor" -bg "$bgcolor" "$@""

dzen_tmp="^ca(1, %s)%s^ca()"
output_tmp="%s:%s%s"
separator="|"

function join_by()
{
   local spt="$1"
   
   shift
   res=$(printf "$spt%s" "$@")
   echo ${res:${#spt}}
}

TEMP="$( printf "$output_tmp" "Temp" "$(($(cat /sys/class/thermal/thermal_zone0/temp)/1000))" "C" )"

TIME="$( printf "$dzen_tmp" "./calendar.sh" "$(date '+%e %b %y %a | %R')" )"

used_ram=$(free -m | grep '^Mem' | tr -s ' ' | cut -d ' ' -f3)
total_ram=$(free -m | grep '^Mem' | tr -s ' ' | cut -d ' ' -f2)
#used_ram_h=$(free -h | grep '^Mem' | tr -s ' ' | cut -d ' ' -f3)
RAM="$( printf "$output_tmp" "RAM" "$(perl -e "printf(\"%.f\", $used_ram / $total_ram * 100)")" "%" )"	# % of used memory 

UPTIME=$(uptime | sed 's/.*: //; s/,//g')

CPU="$( printf "$output_tmp" "CPU" "$(top -bn 2 -d 0.1 | grep '^%Cpu' | tail -n 1 | gawk '{print $2+$4+$6}')" "%" )"

#vol=$(amixer -m get master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')

BAT="$( printf "$output_tmp" "Bat" "$(acpi -b | awk -F '[,:] ' '{if ($2=="Charging") print $3" (+)"; else if ($2=="Discharging") print $3" (-)"; else print $3}')" "%" )"

LAYOUT=$( (( ( 16#$(xset q | grep led | awk '{print $10}') & 16#1000 ) == 16#1000 )) && echo RU || echo EN )

# Array with info elements
info_elements=( "$CPU" "$RAM" "$TEMP" "$BAT" "$LAYOUT" "$TIME" )

join_by "$separator" "${info_elements[@]}" | $dzencmd
