#!/bin/bash
#
# Show shutdown menu via dmenu
# 

main() {
    local actions=("reboot\nshutdown\nsleep\nhibernate")
    local action=$(echo -e $actions | dmenu "$@")
    case "$action" in
    reboot)
        sudo systemctl reboot
        ;;
    shutdown)
        sudo systemctl poweroff

        ;;
    sleep)
        sudo systemctl suspend
        ;;
    hibernate)
        sudo systemctl hibernate
        ;;
    esac
}

main "$@"
