#!/bin/bash
#
# List repositories and jump to corresponding directory
#

main() {
    declare -A local gitdic

    local dirlist=()
    local term="urxvt"

    local except_dirs=(".vim")

    for dir in "${except_dirs[@]}"; do 
        local except_dirs_str+=" -not -path *${dir}*"
    done

    while IFS= read -d $'\0' -r file ; do
        local dir=$(basename "$(dirname "$file")")
        gitdic["$dir"]="$(dirname "$file")"
        dirlist+="$dir\n"
    done < <(find ~ /etc -maxdepth 4 -type d $except_dirs_str -name .git -print0 2>&-)

    #Delete last \n from dirlist
    dirlist="${dirlist%'\n'}"

    local choice=$(echo -e "$dirlist" | sort | dmenu "$@")
    [ -n "$choice" ] && ( cd "${gitdic["$choice"]}"; $term )
}

main "$@"
