#!/bin/bash
#
# Google Search using dmenu
#

main() {
    local url='https://www.google.ru/search?q='

    local selection=$(xclip -selection c -o)
    (xclip -selection c -o -t TARGETS | grep image 1>&-) && selection=
    local query=$( printf "$selection" | dmenu -p "Search" )
    [ -n "$query" ] && xdg-open "${url}${query}" 2> /dev/null
}

main "$@"
