#!/bin/bash

main() {
    local path=~/Pictures/screenshots/$(date +%F_%H%M%S_%N).png

    local activeWinId=$(xdotool getactivewindow)
    maim -i $activeWinId "$path"
    xclip -selection clipboard -t image/png "$path"
    notify-send "PrintScreen" "Active window image saved to ${path}"
}

main "$@"
