#!/bin/bash

main() {
    local path=~/Pictures/screenshots/$(date +%F_%H%M%S_%N).png

    maim -s "$path"
    xclip -selection clipboard -t $(xdg-mime query filetype "$path") "$path" 
    # notify if selected otherwise do nothing
    ((! $?)) && notify-send "PrintScreen" "Selected area image saved to ${path}"
}

main "$@"
