#!/bin/bash

main() {
    local path=~/Pictures/screenshots/$(date +%F_%H%M%S_%N).png

    maim "$path"
    xclip -selection clipboard -t image/png "$path"
    notify-send "PrintScreen" "Screen image saved to ${path}"
}

main "$@"
